openapi: 3.0.3
info:
  title: Music Posters API
  version: 1.0.0
  description: |
    This is the API documentation for the music posters API. (Copied from the ms-music-posters API)
    It includes security schemes and reusable components for error responses.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://my.localserver.dev
    description: Local Development Server
tags:
  - name: posters
    description: Operations related to music posters
paths:
  /v1/poster:
    post:
      operationId: create-new-music-poster
      summary: Create a new music poster
      tags:
        - posters
      security: []
      parameters:
        - $ref: '#/components/parameters/Content-Type'
      requestBody:
        $ref: '#/components/requestBodies/CreatePosterRequest'
      responses:
        201:
          $ref: '#/components/responses/PosterResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        404:
          $ref: '#/components/responses/NotFoundError'
        500:
          $ref: '#/components/responses/InternalServerError'
    get:
      operationId: get-all-posters
      summary: Get all music posters
      security: []
      tags:
        - posters
      parameters:
        - $ref: '#/components/parameters/FilterBy'
        - $ref: '#/components/parameters/PageNumber'
        - $ref: '#/components/parameters/PageSize'
        - $ref: '#/components/parameters/SortBy'
        - $ref: '#/components/parameters/OrderBy'
      responses:
        200:
          $ref: '#/components/responses/ListPostersResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        404:
          $ref: '#/components/responses/NotFoundError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /v1/poster/{id}:
    get:
      operationId: get-music-poster-details-by-id
      summary: Get music poster details by its ID
      security: []
      tags:
        - posters
      parameters:
        - $ref: '#/components/parameters/PosterId'
      responses:
        200:
          $ref: '#/components/responses/PosterResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        404:
          $ref: '#/components/responses/NotFoundError'
        500:
          $ref: '#/components/responses/InternalServerError'
    patch:
      operationId: update-music-poster-by-id
      summary: Update a music poster by its ID
      security: []
      tags:
        - posters
      parameters:
        - $ref: '#/components/parameters/PosterId'
        - $ref: '#/components/parameters/Content-Type'
      requestBody:
        $ref: '#/components/requestBodies/UpdatePosterRequest'
      responses:
        200:
          $ref: '#/components/responses/PosterResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        404:
          $ref: '#/components/responses/NotFoundError'
        500:
          $ref: '#/components/responses/InternalServerError'
    delete:
      operationId: delete-music-poster-by-id
      summary: Delete a music poster by its ID
      security: []
      tags:
        - posters
      parameters:
        - $ref: '#/components/parameters/PosterId'
      responses:
        200:
          $ref: '#/components/responses/DeletePosterResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        404:
          $ref: '#/components/responses/NotFoundError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  parameters:
    Content-Type:
      name: Content-Type
      in: header
      required: true
      schema:
        type: string
        enum:
          - application/vnd.api+json
    PosterId:
      name: id
      in: path
      required: true
      schema:
        type: string
        format: uuid
    FilterBy:
      name: filter
      in: query
      style: deepObject
      explode: true
      required: false
      schema:
        type: object
        properties:
          id:
            type: string
            format: uuid
          name:
            type: string
          description:
            type: string
          event_date:
            type: string
            format: date-time
    PageNumber:
      name: page[number]
      in: query
      required: false
      schema:
        type: integer
        format: int
        minimum: 1
        default: 1
    PageSize:
      name: page[size]
      in: query
      required: false
      schema:
        type: integer
        format: int
        minimum: 1
        maximum: 100
        default: 10
    SortBy:
      name: sort
      in: query
      required: false
      schema:
        type: string
        enum: [id, name, description, event_date, created_at, updated_at]
    OrderBy:
      name: order
      in: query
      required: false
      schema:
        type: string
        enum: [asc, desc]
  requestBodies:
    CreatePosterRequest:
      description: "Poster object that needs to be added to the store"
      required: true
      content:
        application/vnd.api+json:
          schema:
            type: object
            required:
              - data
            properties:
              data:
                type: object
                required:
                  - type
                  - attributes
                properties:
                  type:
                    $ref: '#/components/schemas/PosterType'
                  attributes:
                    type: object
                    required:
                      - name
                      - description
                      - event_date
                      - image
                    properties:
                      name:
                        $ref: '#/components/schemas/PosterName'
                      description:
                        $ref: '#/components/schemas/PosterDescription'
                      event_date:
                        $ref: '#/components/schemas/PosterEventDate'
                      image:
                        $ref: '#/components/schemas/FileBase64Encoded'
            example:
              data:
                type: "posters"
                attributes:
                  name: "Music Poster"
                  description: "A music poster"
                  event_date: "2025-01-01T00:00:00+00:00"
                  image: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAA7EAAAOxAGVKw4bAAABaElEQVRIie2Vv0oDQRDGv"
    UpdatePosterRequest:
      description: "Poster object that needs to be updated in the store"
      required: true
      content:
        application/vnd.api+json:
          schema:
            type: object
            required:
              - data
            properties:
              data:
                type: object
                required:
                  - type
                  - id
                  - attributes
                properties:
                  type:
                    $ref: '#/components/schemas/PosterType'
                  id:
                    $ref: '#/components/schemas/PosterId'
                  attributes:
                    type: object
                    required:
                      - name
                      - description
                      - event_date
                    properties:
                      name:
                        $ref: '#/components/schemas/PosterName'
                      description:
                        $ref: '#/components/schemas/PosterDescription'
                      event_date:
                        $ref: '#/components/schemas/PosterEventDate'
                      image:
                        $ref: '#/components/schemas/FileBase64Encoded'
            example:
              data:
                type: "posters"
                id: "d290f1ee-6c54-4b01-90e6-d701748f0851"
                attributes:
                  name: "Music Poster"
                  description: "A music poster"
                  event_date: "2025-01-01 00:00:00"
                  image: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAA7EAAAOxAGVKw4bAAABaElEQVRIie2Vv0oDQRDGv"
  responses:
    PosterResponse:
      description: Poster details response
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Poster'
          example:
            data:
              type: "posters"
              id: "d290f1ee-6c54-4b01-90e6-d701748f0851"
              attributes:
                name: "Music Poster"
                description: "A music poster"
                image: "https://music-posters.s3.storage.amazonaws.com/bucket/key/image.png"
                event_date: "2025-01-01T00:00:00+00:00"
                created_at: "2025-01-01T00:00:00+00:00"
                updated_at: null
              links:
                self: "https://api-music-posters.spinettabox.dev/v1/posters/d290f1ee-6c54-4b01-90e6-d701748f0851"
    DeletePosterResponse:
      description: Poster deleted response
      content:
        application/vnd.api+json:
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  id:
                    $ref: '#/components/schemas/PosterId'
    ListPostersResponse:
      description: List Posters response
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Posters'
          example:
            data:
              - type: "posters"
                id: "d290f1ee-6c54-4b01-90e6-d701748f0851"
                attributes:
                  name: "Music Poster"
                  description: "A music poster"
                  image: "https://music-posters.s3.storage.amazonaws.com/bucket/key/image.png"
                  event_date: "2025-01-01T00:00:00+00:00"
                  created_at: "2025-01-01T00:00:00+00:00"
                  updated_at: "2025-01-01T00:00:00+00:00"
                links:
                  self: "https://api-music-posters.spinettabox.dev/v1/posters/d290f1ee-6c54-4b01-90e6-d701748f0851"
              - type: "posters"
                id: "d290f1ee-6c54-4b01-90e6-d701748f0852"
                attributes:
                  name: "Music Poster 2"
                  description: "Another music poster"
                  image: "https://music-posters.s3.storage.amazonaws.com/bucket/key/image.png"
                  event_date: "2025-01-01T00:00:00+00:00"
                  created_at: "2025-01-01T00:00:00+00:00"
                  updated_at: null
                links:
                  self: "https://api-music-posters.spinettabox.dev/v1/posters/d290f1ee-6c54-4b01-90e6-d701748f0852"
            meta:
              total: 2
    BadRequestError:
      description: Bad request
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            errors:
              - code: '400'
                source:
                  pointer: '/v1/posters/{id}'
                title: 'Bad request'
                detail: 'Invalid request, please check the request body'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            errors:
              - code: '401'
                source:
                  pointer: '/v1/posters/{id}'
                title: 'Unauthorized'
                detail: 'You are not authorized to access this resource'
    NotFoundError:
      description: Not found
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            errors:
              - code: '404'
                source:
                  pointer: '/v1/posters/{id}'
                title: 'NotFound'
                detail: 'The resource you requested was not found'
    InternalServerError:
      description: Internal server error
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            errors:
              - code: '500'
                source:
                  pointer: '/v1/posters/{id}'
                title: 'ServerError'
                detail: 'An internal server error occurred'
  schemas:
    CreatedAt:
      type: string
      format: date-time
      readOnly: true
      x-faker: date.past
    UpdatedAt:
      type: string
      format: date-time
      readOnly: true
      nullable: true
      x-faker: date.recent
    Error:
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              code:
                description: >-
                  An application-specific error code, expressed as a string value.
                type: string
              source:
                type: object
                properties:
                  pointer:
                    description: >-
                      A JSON Pointer [RFC6901] to the associated entity in the request
                      document [e.g. `/data` for a primary data object, or
                      `/data/attributes/title` for a specific attribute].
                    type: string
              title:
                description: >-
                  A short, human-readable summary of the problem.
                type: string
              detail:
                description: >-
                  A human-readable explanation specific to this occurrence of the
                  problem.
                type: string
    FileBase64Encoded:
      description: "Base64 encoded file string"
      type: string
      format: binary
    PosterId:
      type: string
      format: uuid
      readOnly: true
      x-faker: random.uuid
    PosterImage:
      type: string
      format: uri
      x-faker: image.imageUrl
    PosterDescription:
      type: string
      x-faker: commerce.productDescription
    PosterName:
      type: string
      x-faker: commerce.productName
    PosterType:
      type: string
      enum:
        - poster
    PosterEventDate:
      type: string
      format: date-time
      x-faker: date.future
    Poster:
      type: object
      properties:
        data:
          type: object
          properties:
            type:
              $ref: '#/components/schemas/PosterType'
            id:
              $ref: '#/components/schemas/PosterId'
            attributes:
              type: object
              properties:
                name:
                  $ref: '#/components/schemas/PosterName'
                description:
                  $ref: '#/components/schemas/PosterDescription'
                image:
                  $ref: '#/components/schemas/PosterImage'
                event_date:
                  $ref: '#/components/schemas/PosterEventDate'
                created_at:
                  $ref: '#/components/schemas/CreatedAt'
                updated_at:
                  $ref: '#/components/schemas/UpdatedAt'
            links:
              type: object
              properties:
                self:
                  $ref: '#/components/schemas/SelfLink'
    Posters:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              type:
                $ref: '#/components/schemas/PosterType'
              id:
                $ref: '#/components/schemas/PosterId'
              attributes:
                type: object
                properties:
                  image:
                    $ref: '#/components/schemas/PosterImage'
                  name:
                    $ref: '#/components/schemas/PosterName'
                  description:
                    $ref: '#/components/schemas/PosterDescription'
                  event_date:
                    $ref: '#/components/schemas/PosterEventDate'
                  created_at:
                    $ref: '#/components/schemas/CreatedAt'
                  updated_at:
                    $ref: '#/components/schemas/UpdatedAt'
              links:
                type: object
                properties:
                  self:
                    $ref: '#/components/schemas/SelfLink'
        meta:
          $ref: '#/components/schemas/Meta'
    SelfLink:
      type: string
      format: uri
      x-faker: internet.url
    Meta:
      type: object
      properties:
        total:
          type: integer
          x-faker:
            random.number:
              min: 1
              max: 100